baseURL = "/" #"https://markn2000.com/markn-homepage/"
languageCode = "ja-jp"
title = "MarkN's HomePage"
defaultContentLanguage = "ja"

# メニュー設定は後で行います
# [menu]
#   [[menu.main]]
#     identifier = "about"
#     name = "About"
#     url = "/about/"
#     weight = 1

# 他のオプションは必要に応じて後から追加していきます