baseURL = "/" #"https://markn2000.com/markn-homepage/"
languageCode = "ja-jp"
title = "MarkN's HomePage"
defaultContentLanguage = "ja"

# hugo.toml
buildStats = true

[params]
  [params.author]
    name = "まーくん。(MarkN)のホームページ" # ヘッダーに表示するサイト名
    profileName = "まーくん。(MarkN)" # プロフィール画像横などに表示する名前
    bio = "Resoniteでプログラミングなどをしてツールやおもちゃを作っています"

# メニュー設定は後で行います
# [menu]
#   [[menu.main]]
#     identifier = "about"
#     name = "About"
#     url = "/about/"
#     weight = 1

# 他のオプションは必要に応じて後から追加していきます