baseURL = "/"
languageCode = "ja-jp"
title = "まーくん。(MarkN)のホームページ"

[params]
  description = "Resoniteでプログラミングなどをしてツールやおもちゃを作っています" # この行

[markup.goldmark.renderer]
  unsafe = true

[build]
  [build.processing]
    [build.processing.css]
      [build.processing.css.postcss]
        # config = "./postcss.config.js"