baseURL = "http://example.org/" # 将来的に実際のドメインに変更
languageCode = "ja-jp"
title = "まーくん。(MarkN)のホームページ"
# copyright = "© 2025 MarkN. All Rights Reserved." # フッターで .Site.Copyright も使える

[params]
  description = "Resoniteでプログラミングなどをしてツールやおもちゃを作っています。技術的な知見やTipsも発信。"
  og_image = "/images/profile.webp"
  # author = "まーくん。(MarkN)"
  mainSections = ["posts"]

paginate = 5

[markup]
  [markup.goldmark.renderer]
    unsafe = true # HTMLタグをMarkdown内で許可する場合
  [markup.highlight]
    # anchorLineNos = false
    codeFences = true # ``` で囲むコードブロックをハイライト
    # guessSyntax = false
    # hl_Lines = ''
    # lineAnchors = ''
    lineNos = false # 行番号を表示するかどうか (true/false)
    # lineNumbersInTable = true
    noClasses = false # falseにするとChromaが生成するクラス名が付与される
    style = "monokai" # ハイライトスタイル (例: "monokai", "native", "fruity"など多数)
    # tabWidth = 4

[build]
  [build.processing]
    [build.processing.css]
      [build.processing.css.postcss]
        # config = "./postcss.config.js"