baseURL = "/"
languageCode = "ja-jp"
title = "まーくん。(MarkN)のホームページ"

[params]
  description = "Resoniteでプログラミングなどをしてツールやおもちゃを作っています"
  mainSections = ["posts"]

paginate = 5

[markup]
  [markup.goldmark.renderer]
    unsafe = true # HTMLタグをMarkdown内で許可する場合
  [markup.highlight]
    # anchorLineNos = false
    codeFences = true # ``` で囲むコードブロックをハイライト
    # guessSyntax = false
    # hl_Lines = ''
    # lineAnchors = ''
    lineNos = false # 行番号を表示するかどうか (true/false)
    # lineNumbersInTable = true
    noClasses = false # falseにするとChromaが生成するクラス名が付与される
    style = "monokai" # ハイライトスタイル (例: "monokai", "native", "fruity"など多数)
    # tabWidth = 4

[build]
  [build.processing]
    [build.processing.css]
      [build.processing.css.postcss]
        # config = "./postcss.config.js"