backend:
  name: github
  repo: MarkN2000/markn-homepage # あなたのリポジトリ
  branch: main # あなたのブランチ
  auth_type: pkce
  app_id: Ov23libiHDH0Lfpwyj5n # あなたのApp ID
  cms_label_prefix: "content/posts/" # 任意: Decap CMSのUIでパスのプレフィックスを分かりやすくする場合

# media_folder と public_folder は、ひとまずコメントアウトするか、
# 非常にシンプルな固定パスを指定
media_folder: "static/images/uploads_test"
public_folder: "/images/uploads_test"

# collections は一旦空にするか、非常にシンプルなものを一つだけ定義
collections:
  - name: "test_posts"
    label: "Test Posts"
    folder: "content/test_posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}