backend:
  name: github
  repo: MarkN2000/markn-homepage # あなたのリポジトリ
  branch: main # あなたのブランチ
  base_url: https://markn-homepage.pages.dev # Cloudflare PagesのURL (Functionsがこの配下で動作する場合)
  auth_endpoint: api/auth # 認証開始エンドポイントへのパス (例)

# media_folder と public_folder は、ひとまずコメントアウトするか、
# 非常にシンプルな固定パスを指定
media_folder: "static/images/uploads_test"
public_folder: "/images/uploads_test"

# collections は一旦空にするか、非常にシンプルなものを一つだけ定義
collections:
  - name: "test_posts"
    label: "Test Posts"
    folder: "content/test_posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}